[package]
name = "miri-rustabi-patcher"
version = "0.1.0"
edition = "2021"
readme = "REAMDE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
